[book]
title = "Mikhail Semyonovich Tsvet the founder of chromatography"
authors = [
    "Evgenia Mikhailovna Senchenkova (Author)",
    "Giorgi Vladimirovich Kazakov (Editor)",
    "Roman Alexandrovich Sidorov (Editor)",
]
description = "Mikhail Semyonovich Tsvet the founder of chromatography"

[output.html]
additional-css = ["theme/css/language-picker.css"]
git-repository-url = "https://github.com/kgv/MikhailSemyonovichTsvetTheFounderOfChromatography"

# EPUB
# [output.epub]

# PDF
# [output.pdf]

# [output.pandoc]

# DOCX
# [output.pandoc.profile.docx]
# output-file = "output.docx"

# LATEX
# [output.pandoc.profile.latex]
# output-file = "output.tex"
# pdf-engine = "xelatex"

# [output.pandoc.profile.latex.variables]
# fontenc = "T2A"
# lang = "ru-RU"
# mainfont = "Liberation Serif"
# header-includes = [
#     # "\\raggedright" # Выровнять текст по левому краю
#     "\\sloppy", # "Разрешаю делать пробелы между словами какими угодно большими, главное — не вылезай за правый край страницы"
#     "\\usepackage[none]{hyphenat}",
#     "\\usepackage{alphabeta}",
#     "\\usepackage{lineno}", # For line numbering
#     "\\linenumbers",
#     "\\usepackage{grffile}", # точки в именах файлов
#     "\\graphicspath{{../../../}}", # исправление путей
# ]
