[formatting]
reorder_arrays = true
reorder_keys = true

# https://rust-lang.github.io/mdBook/format/configuration/general.html
[[rule]]
include = ["**/book.toml"]
keys = ["book"]
formatting = { reorder_keys = false }
